from app.utils.schemas.validate_schema_for_get import validate_schema_for_get
from app.utils.schemas.validate_schema_for_post import validate_schema_for_post
from app.utils.schemas.weather_forecasts_schema import WeatherForecastSchema
